services:
  lsr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lsr-app
    restart: unless-stopped
    ports:
      - "8080:80"          # Expose HTTP internally; NPM will proxy here
    volumes:
      - .:/var/www
      - ./scripts:/var/www/scripts
    networks:
      - main_network       # join existing network

networks:
  main_network:
    external: true        # tells Docker to use an existing network
